### ISSUE TITLE
Can I use this tool to do scene text detection + recognition ?

### ISSUE THREAD

**Issue by lomograb** [tmbdev/clstm#135]
I wonder if I could train the network with pieces of grayscaled image from camera instead of black-in-white document only. Do LSTM has coverage about this case ?

**Comment by wanghaisheng** [comment]
maybe [this one](https://github.com/bear63/sceneReco) would be helpful

**Comment by lomograb** [comment]
I just discover that crnn is incredibly slow. It took about 3 seconds per pieces of an image to recognize all the texts. So if I have 10 text boxes in an image, it would take 30~ seconds to finish
