### ISSUE TITLE
Is it possible to train multiple languages on a one model file ?

### ISSUE THREAD

**Issue by lomograb** [tmbdev/clstm#136]

**Comment by amitdo** [comment]
Yes, but each script should be in a separate line.

**Comment by amitdo** [comment]
For mixed scripts in the same line see this paper: 
https://www.researchgate.net/publication/280777013_A_Sequence_Learning_Approach_for_Multiple_Script_Identification

**Comment by lomograb** [comment]
Does CLSTM support this (mixed scripts in the same line) ?

**Comment by amitdo** [comment]
It's not supported out-of-the-box, but you can implement what's described in that paper with clstm.

**Comment by lomograb** [comment]
Thank you @amitdo for replying and this great project too. Okay, going to close this issue

**Comment by mittagessen** [comment]
As a note there is a model for doing the script identification exactly as described in the article (arrived upon independently) at [kraken-models](https://github.com/mittagessen/kraken-models/tree/master/clstm/script-detection). It is able to differentiate between Arabic, Syriac, Cyrillic, Greek, Latin, and Fraktur.
