### ISSUE TITLE
proto for the python version

### ISSUE THREAD

**Issue by BestSonny** [tmbdev/clstm#22]
Is there anybody who has written protobuf code for the python wrapper?

**Comment by mittagessen** [comment]
Have a look at [this tree](https://github.com/mittagessen/clstm/tree/python_bindings). It's untested as I haven't gotten around to convert images to Sequence objects yet but loading a serialized network returns an INetwork instance looking reasonable.

**Comment by BestSonny** [comment]
Thank you for that.This would be a lot of helps.

**Comment by amitdo** [comment]
@BestSonny, I believe commit 54d8b6332f solved the issue:
 Modifications to setup and save_net/load_net to make them available from Python.

**Comment by tmbdev** [comment]
Yes, sorry about that omission.

(Actually, I had misread the bug report initially, thinking that you were asking for code to read CLSTM-trained models into Python; that would also be useful, but is a lot harder.)
