### ISSUE TITLE
What's the meaning of the argument skip?

### ISSUE THREAD

**Issue by edward-zhu** [tmbdev/clstm#29]
Hi @tmbdev,

I am trying to figure out how the CTC works in clstm and got stuck.

I'm confused when looking into the following code in `ctc.cc`.

``` C++
void forward_algorithm(Mat &lr, Mat &lmatch, double skip) {
    int n = ROWS(lmatch), m = COLS(lmatch);
    lr.resize(n, m);
    Vec v(m), w(m);
    for (int j = 0; j < m; j++) v(j) = skip * j;
    for (int i = 0; i < n; i++) {
        w.segment(1, m-1) = v.segment(0, m-1);
        w(0) = skip * i;
        for (int j = 0; j < m; j++) {
            Float same = log_mul(v(j), lmatch(i, j));
            Float next = log_mul(w(j), lmatch(i, j));
            v(j) = log_add(same, next);
        }
        lr.row(i) = v;
    }
}
```

I'm wondering what the argument `skip` means since it not in the original thesis of Graves nor in the source code of rnnlib.

Thanks!

**Comment by tmbdev** [comment]
It's the cost of skipping states at the beginning of the match. To get the same behavior as Graves' thesis, you probably should set that to a large value.
