### ISSUE TITLE
test file for ctc.

### ISSUE THREAD

**Issue by clive-g-brown** [tmbdev/clstm#3]
would be good to have one. the files generated seem to be only for seq.

**Comment by tmbdev** [comment]
I'll add more samples and documentation with the next couple of updates.

**Comment by clive-g-brown** [comment]
Great thanks.

Sent from my iPad

On 7 Mar 2015, at 18:45, Tom <notifications@github.com<mailto:notifications@github.com>> wrote:

I'll add more samples and documentation with the next couple of updates.

**Comment by tmbdev** [comment]
There are test files now, plus iPython notebooks illustrating how to write HDF5 training files.
