### ISSUE TITLE
Error building the Python extension

### ISSUE THREAD

**Issue by ghost** [tmbdev/clstm#39]
Hi,
Building the python extension  (python setup.py build) failed  : 

clstm_wrap.cpp: In function ‘PyObject\* _wrap_INetwork_d_inputs_set(PyObject_, PyObject_)’:
clstm_wrap.cpp:11749:21: error: ‘struct ocropus::INetwork’ has no member named ‘d_inputs’
   if (arg1) (arg1)->d_inputs = _arg2;
                     ^
clstm_wrap.cpp: In function ‘PyObject_ _wrap_INetwork_d_inputs_get(PyObject_, PyObject_)’:
clstm_wrap.cpp:11783:35: error: ‘struct ocropus::INetwork’ has no member named ‘d_inputs’
   result = (Sequence _)& ((arg1)->d_inputs);
                                   ^
clstm_wrap.cpp: In function ‘PyObject_ _wrap_INetwork_d_outputs_set(PyObject_, PyObject_)’:
clstm_wrap.cpp:11825:21: error: ‘struct ocropus::INetwork’ has no member named ‘d_outputs’
   if (arg1) (arg1)->d_outputs = _arg2;
                     ^
clstm_wrap.cpp: In function ‘PyObject_ _wrap_INetwork_d_outputs_get(PyObject_, PyObject_)’:
clstm_wrap.cpp:11859:35: error: ‘struct ocropus::INetwork’ has no member named ‘d_outputs’
   result = (Sequence _)& ((arg1)->d_outputs);
                                   ^
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
clstm_wrap.cpp: In function ‘PyObject_ _wrap_INetwork_d_inputs_set(PyObject_, PyObject_)’:
clstm_wrap.cpp:11749:21: error: ‘struct ocropus::INetwork’ has no member named ‘d_inputs’
   if (arg1) (arg1)->d_inputs = _arg2;
                     ^
clstm_wrap.cpp: In function ‘PyObject_ _wrap_INetwork_d_inputs_get(PyObject_, PyObject_)’:
clstm_wrap.cpp:11783:35: error: ‘struct ocropus::INetwork’ has no member named ‘d_inputs’
   result = (Sequence _)& ((arg1)->d_inputs);
                                   ^
clstm_wrap.cpp: In function ‘PyObject_ _wrap_INetwork_d_outputs_set(PyObject_, PyObject_)’:
clstm_wrap.cpp:11825:21: error: ‘struct ocropus::INetwork’ has no member named ‘d_outputs’
   if (arg1) (arg1)->d_outputs = _arg2;
                     ^
clstm_wrap.cpp: In function ‘PyObject_ _wrap_INetwork_d_outputs_get(PyObject_, PyObject_)’:
clstm_wrap.cpp:11859:35: error: ‘struct ocropus::INetwork’ has no member named ‘d_outputs’
   result = (Sequence *)& ((arg1)->d_outputs);

**Comment by tmbdev** [comment]
Yes, I'm in the middle of converting to Eigen::Tensor. I should probably have created a branch, but I had hoped it would go a bit quicker than it has.

Use tag a588c8 for now.

**Comment by tmbdev** [comment]
OK, it's been fixed now.
You can also use the old "separate-derivs" branch if you depend on the old representation.

**Comment by ghost** [comment]
Yes -> everything works fine now.
Thank you for your great work !
