### ISSUE TITLE
[Feature request] Add option to clstmtrainocr to load previous trained model.

### ISSUE THREAD

**Issue by amitdo** [tmbdev/clstm#41]

**Comment by amitdo** [comment]
ocropy has this feature with the 'load' parameter to  ocropus-rtrain

**Comment by amitdo** [comment]
I also request to implement this feature for clstmfiltertrain.
The older clstmtext program already implements this.

**Comment by tmbdev** [comment]
It's pretty easy to add; could you send me a patch?

**Comment by amitdo** [comment]
OK. I've written the code. I will submit a pull-request soon.
