### ISSUE TITLE
Other language trial report

### ISSUE THREAD

**Issue by isaomatsunami** [tmbdev/clstm#49]
With 500-character subset of Japanese Kanji, clstm works fine. (hidden_nodes = 100, MacBook, gcc48 from homebrew)
Your kid reads Japanese brilliantly.

I am trying 2492-char subset. it seems to take several weeks (hidden=200, this time)
(NO nhidden = 200 seems to be hopeless, he/she seems to learn one char by forgetting another)

Now trying 3700 chars( little bigger tesseract jp-dataset ) with nhidden = 800 and nhidden =1200.
Unless my PC broke, I will see the result next spring.

**Comment by amitdo** [comment]
How much time did it take you to train 500 chars?

**Comment by isaomatsunami** [comment]
One-day training is enough to predict 500 chars.
Seems that the current Eigen.Tesor version runs in a single thread. My setting might be wrong. 

in run-uw3-500, hidden may be nhidden, it seems to be renamed.

**Comment by isaomatsunami** [comment]
After 50 days of training on my MacBookPro, 130000 iterations, against 3877 classes  of characters, the clstm has achieved 3.6% error rate so far.
3877 codec set is comprised of tesseract-ocr Japanese set + a little addition( tesseract set lacks some non-authentic characters usually seen in daily documents).
The hidden nodes is 800, The trained data is 58.2MB. (I can't upload!!!)
No hangup. Bravo to both tmbdev and Intel/Apple.

**Comment by amitdo** [comment]
Cool !
:)

**Comment by zuphilip** [comment]
<blockquote>The trained data is 58.2MB. (I can't upload!!!)</blockquote>

@isaomatsunami Why do you can't upload it?

**Comment by isaomatsunami** [comment]
I thought the limit size of Github was 50MB...
The performance is fluctuating now. When stabilized, I will upload it.

It seems many of errors are inevitable/acceptable,  between "W" and "Ｗ"(Japanese wide char) , between "," and "、" and so on.

**Comment by zuphilip** [comment]
Currently, I read that file size limit in github is 100 MB, see https://help.github.com/articles/what-is-my-disk-quota/ . Thank you for sharing the file.

**Comment by isaomatsunami** [comment]
uploaded trained data for Japanese character set. I'm not sure it works with current code.
https://github.com/isaomatsunami/clstm-Japanese

**Comment by wanghaisheng** [comment]
@isaomatsunami how  do you get single tex-line from your original documents

**Comment by zuphilip** [comment]
@wanghaisheng Maybe my wiki page [Working with Ground Truth](https://github.com/tmbdev/ocropy/wiki/Working-with-Ground-Truth) helps here.

**Comment by wanghaisheng** [comment]
@zuphilip  can you show me which paragraph you refer to  ?

**Comment by ghost** [comment]
@isaomatsunami what was your lrate=? and hidden=?
