### ISSUE TITLE
loading of previously trained models

### ISSUE THREAD

**Issue by stexandev** [tmbdev/clstm#52]
Hi, 
I have an issue concerning the master-branch, where loading of trained models into clstmocrtrain is implemented but not working (for me). I have audited the code but cannot find what issues the following error with a given load- and/or start-parameter.
got 950 files, 50 tests
.Stacked: 0.0001 0.9 in 0 48 out 0 74
FATAL: missing parameter

Best wishes

**Comment by amitdo** [comment]
Please paste here the full commands you used to:
- Train the model
- Load the model

**Comment by stexandev** [comment]
The  bash-script I used contains the following commands for training (loading-attempt was made with commented lines)
#!/bin/bash
set -x
set -a
report_every=10
save_every=1000
ntrain=200000
dewarp=center
display_every=10
test_every=1000
testset=mub1test.h5
hidden=100
lrate=1e-4
save_name=mub1
report_time=1
#load=mub1-12000.clstm
#start=12000
./../clstm-master/clstmocrtrain mub1gt mub1test

**Comment by amitdo** [comment]
If you haven't noticed, I already solved the problem. PR #53 has 1-line fix. You can apply it and recompile. It seems to work as expected now.
Thanks for reporting !

**Comment by amitdo** [comment]
The 'start' environment variable isn't needed in the second run, only the 'load'.

**Comment by isaomatsunami** [comment]
Current code still fails with "FATAL missing parameter"
    at network_info(clstm.net) just after clstm.load().
The first call is OK. but recurrently-called(2nd time) network_info(net, ".Stacked") fails.(with super == 0x0)

This parameter seems to be "learning_rate". Is it stored in saved .clstm file?
Or net->attr must have super instance as default values.

**Comment by amitdo** [comment]
What do you mean by "current code"?
Tom didn't merge my PR with master yet, so if you want to test it you should apply the patch locally (to a new branch) and recompile.

It works for me and for @stexandev.

**Comment by isaomatsunami** [comment]
It's my fault. patched code works perfectly.
Thanks.
