### ISSUE TITLE
Providing manual alignment

### ISSUE THREAD

**Issue by Sleemanmunk** [tmbdev/clstm#56]
Is there any way to give a gold-standard alignment to CLSTMText?
I'm working on some research evaluating its efficacy on other tasks besides OCR, such as Twitter, where expanding acronyms is a big deal. Right now clstmtext is suffering mightily because it takes text lines directly instead of letting me give it the direct alignments (e.g. two sequences, ["lol", "wut"] --> ["laughing out loud", "what"])

Anything I can do to help it on this front?

**Comment by Sleemanmunk** [comment]
I was hoping clstmseq was what I was looking for. Unfortunately, I'm having trouble finding documentation as to what these "sequences" actually are and how to make an aligned list of word sequences into a list of "variable length sequences of fixed length vectors" Why are the inputs "floats?" if they were ints they'd be indices into an alphabet, a paradigm with which I am all too familiar, but I don't know what to do with floats.

**Comment by tmbdev** [comment]
The outputs from the network are "hot-1" coded. That is:

Sequence outputs(nsteps, nclasses, nbatches);
for(int i=0; i<nclasses; i++) outputs[t](i, b) = 0;
outputs[t](cls, b) = 1;

means that the output at time step `t` in batch `b` is class `cls`. (Usually, nbatches=1, but you can train multiple sequences simultaneously.)

Manual segmentation doesn't really help a lot. But what you could do is the following. Let's say your manual segmentation is given as a struct { int x0, x1; int cls; }. Let's also say that your output sequence is Sequence outputs;

Sequence mask(nsteps, nclasses, 1);
for(int t=0; t<nsteps; t++) for(int i=0; i<nclasses; i++) mask[t](i,0) = 0;
for(auto segment : segmentation) {
  for(int t=segment.x0; t<=segment.x1; t++) mask[t](segment.cls) = 1.0;
}
for(int t=0; t<nsteps; t++) for(int i=0; i<nclasses; i++) outputs[t](i,0) *= mask[t](i,0);

Now you can use the masked outputs for CTC alignment and then use the aligned output from that for backpropagation.
