### ISSUE TITLE
Undefined symbol error when "import clstm" in python 

### ISSUE THREAD

**Issue by arthchan2003** [tmbdev/clstm#62]
I tried to compile and "setup.py build" with clstm, when I did

> python
> import clstm

I got "_clstm.so: undefined symbol: _ZN7ocropus14default_deviceE"  The platform is Ubuntu 14.04.  I am using Anaconda python.  

Given the name, I suspect the symbol is related to ocropy, so I tried to install the python packaged of ocropy.  But I still get the same error.   Would anyone mind to give me some hints?  Thanks in advance for your time.   And sorry if this is a trivial issue. 

Arthur

**Comment by tmbdev** [comment]
"ocropus" is also the C++ namespace name, so there is no relationship really to ocropy.

There may be some files missing from the setup.py list of source files; I'll check. The Python bindings are not currently tested regularly.

**Comment by arthchan2003** [comment]
My bad, I later demangled the variable and conclude the same thing. 

In any case, thanks for your time in advance.  Kudo to your great work.

**Comment by stweil** [comment]
Can this issue be closed?
