### ISSUE TITLE
python setup.py build - ERROR

### ISSUE THREAD

**Issue by avr248** [tmbdev/clstm#64]
clstm_wrap.cpp:6375:15: error: no member named 'resize' in 'ocropus::Batch'
      (arg1)->resize(arg2,arg3);
      ~~~~~~  ^
clstm_wrap.cpp:6426:15: error: no member named 'setZero' in 'ocropus::Batch'
      (arg1)->setZero(arg2,arg3);

**Comment by sawwhite** [comment]
We have the some problem

**Comment by sawwhite** [comment]
struct Batch  
void resize(int,int);
  void setZero(int,int);

in file clstm_wrap should be deleted.

**Comment by jmokoistinen** [comment]
Lot of errors while building any idea what's wrong?
/usr/local/include/unsupported/Eigen/CXX11/src/Tensor/TensorArgMax.h:215:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorEvaluator(const XprType& op, const Device& device)
   ^
/usr/local/include/unsupported/Eigen/CXX11/src/Tensor/TensorArgMax.h:231:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& dimensions() const {
   ^
/usr/local/include/unsupported/Eigen/CXX11/src/Tensor/TensorArgMax.h:235:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded(Scalar\* /_data_/) {
   ^
...
...

**Comment by kba** [comment]
https://github.com/tmbdev/clstm/issues/64#issuecomment-203774401

This was adressed in https://github.com/tmbdev/clstm/commit/0dfde5fa91dae505b33e3f936365b33da1500168

**Comment by kba** [comment]
@jmokoistinen If that is still happening, please try with the 3.3-rc1 Eigen release and open a new issue if it's still happening.
