### ISSUE TITLE
import clstm throw _clstm.so: undefined symbol: _ZN7ocropus14default_deviceE"

### ISSUE THREAD

**Issue by simmoncn** [tmbdev/clstm#86]
who can help me to check the exception? or I want to use the python API to use the pre-trained model. who can give me some tips?

**Comment by jbaiter** [comment]
You have to add `batches.cc` and `clstm_compute.cc` to the `sources` list in `setup.py`. With that, it works for me!

**Comment by tmbdev** [comment]
I've fixed the setup.py file and the Python tests should run again.

The notebooks in misc/ still need updating.
