### ISSUE TITLE
How can I speed up the training process using GPU or multi thread on CPU?

### ISSUE THREAD

**Issue by striversist** [tmbdev/clstm#88]
Even if I build the project success using command "scons -j4 gpu=1", it seems the clstmocrtrain still use CPU to train which is realllllly slow.
So is there any option to turn GPU training on? Was the project dead?

**Comment by tmbdev** [comment]
clstm+Eigen can perform the computations on the GPU in principle, but that code hasn't really been tested much, and it turns out there are now better ways to handle LSTM on GPU. I'm working on a new project for high-performance GPU-based OCR.
